
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: anwar36flow
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: anwar36flow
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: anwar36flow
    ports:
      - "8080:80"

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_container
    restart: always
    volumes:
      - ./my_php_project:/var/www/html
    ports:
      - "80:80"

volumes:
  mysql_data: